version: 2.1

jobs:
  nodejs-build:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          name: 'build'
          command: 'npm run build'

workflows:
  nodejs-workflow:
    jobs:
      - nodejs-build
